---
- name: Installs r1soft agent
           
  become: yes 
  become_method: sudo 
  hosts: agent
  tasks: 
    - name: Create repo 
      copy: 
        src: r1soft.repo
        dest: /etc/yum.repos.d 
      
    - name:  Install agent
      package:
        name: serverbackup-enterprise-agent
        state: present
      

    - name: Start agent 
      service:
        name: cdp-agent
        state: restarted
        enabled: yes
      

    - name: stop iptables
      service:
        name: iptables
        state: stopped 
        enabled: no
      

    - name: Get key
      shell: "r1soft-setup --get-key  http://3.84.5.130:8080/"
      












