---
- name: Installs r1soft agent
  become: yes 
  become_method: sudo 
  hosts: agent
  tasks:     
  - name: Create repo 
    copy: 
      src: r1soft.repo
      dest: /etc/yum.repos.d 
    ignore_errors: true  
  - name: 
    shell: " mv /etc/yum.repos.d/Cen*  /tmp "
    ignore_errors: true
  - name: Install agent
    package:
      name: serverbackup-enterprise-agent
      state: present
  - name: Start agent
    service:
      name: cdp-agent
      state: restarted
      enabled: yes
  - name: Get key 
    command: "r1soft-setup --get-key  http://54.242.195.243:8080"
    ignore_errors: true
  - name: stop iptables
    service:
      name: iptables
      state: stopped 
      enabled: no
